- PRD.md
> Initial Markdown file of PRD

- cluster/cluster_level_parameters.go
- config.yaml
- config/config.go
- go.mod
- main.go
- task/task_definition_parameters.go
1 Added validation for parsing the configuration file for scaling manager
> Recommendation validation

- main.go
1. Added the logic to see the if there is a config file change.
> [recommendation_file_watch]

- config/config_test.go
Created unit test cases for configuration validation.
The test cases have coverage: 90.9% of statements.
> [recommendation_validation]

- main.go
- provision/provision.go
- provision/trigger.go
The PR does the following tasks:
1. Fetch the recommendation queue and pick up the first recommendation. Clear the recommendation queue.
2. Trigger the recommendation using the configuration input and operation provided in the recommendation queue.
3. Since we are considering scaling out in our case the recommended task will be scale_up_by_1, call the ScaleOut method.
4. Update the state with each stage of scaling out.
5. Wait for cluster to be in a stable state and once provision is completed update the states accordingly.
6. Spin up a new VM. Identify and log the stages without spinning the VM.
Note: Remove test lines commented as "Remove later"
Fixes #28 #29 #30 #31 #32 #33
> Initial Commit for provisioner

- main.go
- provision/provision.go
- provision/trigger.go
This PR will be merged to dev branch.
This PR contains code changes w.r.t. provisioner module.
> Initial provisioner

- main.go
Merged PR for the logic to see the if there is a config file change.
> Release v0.1 dev

- main.go
Merged the conflict due to file watch logging changes.
> Merge conflict resolution for logging changes

- main.go
- provision/provision.go
- provision/trigger.go
> Using logger module in place of fmt.Printf

- provision/trigger.go
Handled err returned from GetConfig()
> Error handled from GetConfig() function

- simulator/src/app.py
> Fixed stats/current/stat_name endpoint

- simulator/src/config_parser.py
- simulator/src/constants.py
> Fixed file path for config and schema

- simulator/src/app.py
> Simulator violated count and average logic

- simulator/src/app.py
- simulator/src/config_parser.py
- simulator/src/constants.py
- simulator/src/simulator.py
- Endpoint of node addition /provision/addnode
- File based provisioning lock
- Cluster to remain in yellow state for any duration between 10 to 65 seconds to mimic provisioning state
Resolves #74
> Api for cluster provisioning

- simulator/src/app.py
> Fix: avg endpoint failure on less than expected data points

- provision/provision.go
1. Removed mocking and updated log statements
> Removed comments and mock cases

- simulator/tests/test_config_parser.py
> Changed the path parameter to test config files from relative to absolute path

- main.go
- provision/provision.go
- provision/state_functions.go
- provision/trigger.go
1. Logic to store and get provision State in Opensearch
2. Logic in main() to remove GetMasterIp and use CheckIfMaster
3. GetCurrentState and SetState methods update
4. Removed redundant function from trigger.go
5. Changed snake_case to camelCase
6. Updated the desciptions of methods.
7. Removed unused code
8. Added description for State functions
> Global State Update

- provision/mappings.json
Adding mapping file for index creation if it doesn't exists
> Add mappings.json 

- simulator/src/config_parser.py
- simulator/src/errors.py
Created ValidationError class inside errors.py to reraise exceptions occurring during validation of config.yaml.
Resolves #92
> Custom error for config validation failure.

- simulator/src/cluster.py
- simulator/src/config.yaml
- simulator/src/schema.py
- simulator/tests/config_test/config_1_P.yaml
- simulator/tests/config_test/config_2_P.yaml
- simulator/tests/config_test/config_3_P.yaml
- simulator/tests/config_test/config_5_F.yaml
- simulator/tests/config_test/config_6_F.yaml
- simulator/tests/test_config_parser.py
Renamed index_roll_over_size to index_roll_over_size_gb.
Resolves #95
> Rename 'index_roll_over_size' to 'index_roll_over_size_gb'

- main.go
- provision/provision.go
- provision/state_functions.go
- provision/trigger.go
1. Log statements updated with new logger format
2. Removed fmt.Sprintf while passing to logger as it handles by itself
> Updated log statements

- main.go
Added the PollingInterval changes for periodicProvisionCheck function.
> [initial_provisioner]

- simulator/src/app.py
> Fixed key name in /stats/current/<string:stat_name> endpoint response

- simulator/src/app.py
- simulator/src/cluster.py
- simulator/src/config.yaml
- simulator/src/constants.py
- simulator/src/schema.py
- simulator/tests/config_test/config_1_P.yaml
- simulator/tests/config_test/config_2_P.yaml
- simulator/tests/config_test/config_3_P.yaml
- simulator/tests/config_test/config_4_F.yaml
- simulator/tests/config_test/config_5_F.yaml
- simulator/tests/config_test/config_6_F.yaml
- simulator/tests/test_app.py
> Cluster dynamic data via an endpoint.

- simulator/src/app.py
- simulator/src/cluster.py
- simulator/src/config.yaml
- simulator/src/config_parser.py
- simulator/src/constants.py
- simulator/src/data_ingestion.py
- simulator/src/open_search_simulator.py
- simulator/src/schema.py
- simulator/src/search.py
1) Changed the mechanism to populate the data ingestion, search and
search description to accommodate the recent config file changes.
2) Added the class SeachState and Search to handle the new config changes.
3) Reverted back a small logic.
4) Added the logic to add search queries on resource utilization.
> [search-config]

- logger/logger.go
> Support PANIC logs

- simulator/tests/test_config_parser.py
> Test case to config_parser.py 

- simulator/src/app.py
Removing additional remnode logic.
> [release_v0.1_dev]

- main.go
Added the logic to check if the current state is normal, if so then only process the recommendation.
> Updated main.go

- cluster/cluster_level_parameters.go
- main.go
- task/task_definition_parameters.go
1. Added the logic to get the rules responsible and its metric to recommend a task.
2. Added the logic to update the state, such that it can be used.
> Rules Responsible field is populated and updated in state

- cluster/cluster_level_parameters.go
Changed the return type from cluster to clusterDynamic.
> Logic changed for fetching cluster Current

- simulator/src/app.py
- simulator/src/cluster.py
- simulator/src/cluster_dynamic.py
- simulator/src/config.yaml
- simulator/src/plotter.py
- Added disk utilization in the graph
> Restructured Cluster Dynamic Class

- fetchmetrics/fetchClusterMetrics.go
- fetchmetrics/fetchMetrics.go
- fetchmetrics/fetchNodeMetrics.go
- fetchmetrics/purgeOldDocs.go
- utils/utilities.go
- Removed Cluster and Node structure from utilities.go
- Updated the import alias
> Updated the package import to support Scaling Manager integration

- config.yaml
- config/config.go
Added Flag to monitor with logs
> Added Flag to monitor with logs

- main.go
- provision/ansible_scripts/ansible.cfg
- provision/ansible_scripts/docs.py
- provision/ansible_scripts/group_vars/all/all.yml
- provision/ansible_scripts/roles/scale_down/defaults/main.yml
- provision/ansible_scripts/roles/scale_down/handlers/main.yml
- provision/ansible_scripts/roles/scale_down/tasks/main.yml
- provision/ansible_scripts/roles/scale_down/vars/main.yml
- provision/ansible_scripts/roles/scale_up/defaults/main.yml
- provision/ansible_scripts/roles/scale_up/handlers/main.yml
- provision/ansible_scripts/roles/scale_up/tasks/ansible.cfg
- provision/ansible_scripts/roles/scale_up/tasks/install_ansible.yml
- provision/ansible_scripts/roles/scale_up/tasks/main.yml
- provision/ansible_scripts/roles/scale_up/tasks/opensearch.yml
- provision/ansible_scripts/roles/scale_up/tasks/security.yml
- provision/ansible_scripts/roles/scale_up/tasks/tune.yml
- provision/ansible_scripts/roles/scale_up/templates/internal_users.yml
- provision/ansible_scripts/roles/scale_up/templates/jvm.options
- provision/ansible_scripts/roles/scale_up/templates/opensearch-multi-node.yml
- provision/ansible_scripts/roles/scale_up/templates/opensearch.service
- provision/ansible_scripts/roles/scale_up/templates/security_conf.yml
- provision/ansible_scripts/roles/scale_up/templates/tlsconfig.yml
- provision/ansible_scripts/scaleDownPlaybook.yml
- provision/ansible_scripts/scaleUpPlaybook.yml
- provision/callAnsible.go
- provision/provision.go
- provision/scaleUpNode.go
- provision/state_functions.go
- provision/trigger.go
1. Added 2 different roles for scaleup/scaledown
2. Configures the nodes to add/remove node
3. Performs the changes on all other nodes necessary after scaleup/scaledown
4. Added go methods to call ansible scripts
5. Added flag to monitor with logs
> Ansible scripts to scaleup/down & Integration

- provision/provision.go
- provision/trigger.go
> Pass global Opensearch client

- GNUmakefile
Created GNUmakefile to build and package the scaling_manager.
make build PLATFORM=linux
make pack PLATFORM=linux
make install
> [makefile]

- opensearch/apiCalls.go
- opensearch/mappings.json
- opensearch/osConnection.go
- utilities/utilities.go
1. Added opensearch package
2. Added utilities package
> Opensearch/Utility Code

- opensearch/apiCalls.go
- opensearch/osConnection.go
1. opensearch package renamed to osutils
2. Embedding mappings.json into binary
> Updated package name

- fetchmetrics/fetchClusterMetrics.go
- fetchmetrics/fetchNodeMetrics.go
- fetchmetrics/purgeOldDocs.go
Updated OS package dir in import
> Updated OS package

- cluster/cluster_level_parameters.go
- config.yaml
- config/config.go
- main.go
- recommendation/recommendationEngine.go
1. Ran "go fmt" command to format
2. Updated osUtils package in main.go
3. Updated config.yaml to group some keys
4. Updated Config struct
5. Updated main.go to include config struct changes
> Code format/Config struct update

- config/config.go
Minor bug fix config.ConfigStruct
> Minor bug fix

- cluster/cluster_level_parameters.go
- cluster_sim/cluster_level_parameters.go
- recommendation/recommendationEngine.go
1. Updated return type from []byte to error across the package
> Update return type

- fetchmetrics/fetchNodeMetrics.go
NumShards calculated using cat allocation api
> NumShards calculated

- opensearchUtils/apiCalls.go
1. Added catAllocation method to get number of shards
> catAllocation method

- fetchmetrics/fetchClusterMetrics.go
- fetchmetrics/fetchMetrics.go
- fetchmetrics/fetchNodeMetrics.go
- fetchmetrics/purgeOldDocs.go
Code cleanup and docstring update
> Fetch metrics code cleanup and docstring update

- provision/callAnsible.go
- provision/provision.go
- provision/scaleUpNode.go
- provision/state_functions.go
- provision/trigger.go
1. Logic update from if condition to switch with fallthrough
2. Code cleanup
3. Docstring update
> Provisioner logic and docstring update

- logger/logger.go
Added an environment variable "WD" whoch defines the working directory relative to main.go 
The logger will read the config file relative to this path
> Add ENV variable for config file

- fetchmetrics/fetchNodeMetrics.go
Included MiB and GiB to grep from the top output
> Updated top command

- config.yaml
- recommendation/recommendationEngine.go
1. Updated the metric names in config.yaml
2. Changed validation for metricName
> Changed metric names

- fetchmetrics/fetchNodeMetrics.go
- fetchmetrics/purgeOldDocs.go
Context parameter shifted to be the first
> Context parameter shifted

- opensearchUtils/apiCalls.go
- utilities/utilities.go
Shift context parameter to be the first
> Shift context parameter

- provision/provision.go
- provision/state_functions.go
1. Added setBackToNormal logic to update the state back to normal after provision failed
2. Shifted context paramter
> Added setBackToNormal logic

- cluster/cluster_level_parameters.go
- main.go
- recommendation/recommendationEngine.go
1. Changed the context.Context paramter to be the first param on all the functions.
2. Logic update in main.go
> Context param & main logic updated

- cluster_sim/cluster_level_parameters.go
- main.go
- provision/provision.go
- provision/trigger.go
- recommendation/recommendationEngine.go
1. Changed the calling of simulator URL based on isAccelerated flag.
2. Fixed the issue in main.go
3. Fixed arguement issues in provision.go
4. SimulateShardRebalancing is having time now parameter based on isAccelerated flag.
5. trigger.go sending isAccelerated flag to GetClusterCurrent.
6. Arguement in recommendationEngine to accept isAccelerated flag.
> Accelerating Scaling manager enhancements and fixes.

- main.go
- provision/provision.go
> Bug fix due to merge conflict

- cluster/cluster_level_parameters.go
- config.yaml
- config/config.go
The response returned from the osapi was creating too many open socket connections. 
Closed the response Body after use.
Read the purge time for Fetched Metrics from user config
> Close Response Body & Read purge time

- utilities/utilities.go
1. Close http response Body
2. Fix map[string]string issue
> Opensearch utility close resp body

- recommendation/recommendation_test.go
-Changed test case for updated recommendationEngine.go.
> RecommendationEngine test case

- simulator/src/app.py
- simulator/src/cluster.py
- Added logic to calculate number of days from config file and use it for first simulation
> Accelerated time for shard rebalancing

- main.go
Removed debug code added to debug the number of open file descriptors at each interval
> Removed debug code

- ansible_scripts/group_vars/all/all.yml
- ansible_scripts/roles/scale_down/tasks/main.yml
- ansible_scripts/roles/scale_up/tasks/security.yml
- ansible_scripts/roles/scale_up/templates/internal_users.yml
- ansible_scripts/roles/scale_up/templates/opensearch-multi-node.yml
- provision/callAnsible.go
- provision/provision.go
1. Removed default variables from all.yml
2. Reading the config provided by user in config.yaml
3. Passing the variables by creating a varsFile before calling the provision op
> Ansible config updates

- config.yaml
- config/config.go
Read the configuration keys needed to configure and access Opensearch using ansible scripts
> read ansible config

- recommendation/recommendationEngine.go
Changed warning to debug stmt when there is no recommendation made
> Changed warning to debug stmt

- config.yaml
- recommendation/recommendationEngine.go
Add decision period to the ruleResponsible string
> Add decision period to the ruleResponsible string

- opensearchUtils/mappings.json
- opensearchUtils/osConnection.go
1. Updated index name from "monitor-stats-1" to "monitor-stats"
2. Added missing field into mappings.json
> Index name Update & mappings file update

- fetchmetrics/fetchClusterMetrics.go
- fetchmetrics/fetchNodeMetrics.go
1. Added a new field _documentType
2. Updated StatTag values from ClusterStats and NodesStats to ClusterStatistics and NodeStatistics respectively
> Added field to support SF UI

- opensearchUtils/apiCalls.go
- utilities/utilities.go
1. Added a refresh="wait_for" in index API to ensure the indexing operation waits for a periodic refresh before running the search
2. Fixed nil map interface bug
> wait_for refresh of index and fix nil map issue

- cluster/cluster_level_parameters.go
- config.yaml
Added Max nodes and min nodes into the config file in cluster strict
> Max|Min Nodes check for provisioning

- main.go
- provision/trigger.go
1. Fake master for simulator testing
2. Get NumNodes from simulator endpoint when simFlag is enabled
> Changes to call simulator methods

- ansible_scripts/ansible.cfg
- provision/callAnsible.go
- provision/provision.go
1. Changed the way of passing the extra vars to ansible script from file to map
2. Added log file to log ansible output
3. Mask the credentials from the error message
4. Code optimization to merge separate scaleUp and scaleDown functions into one using switch case
> Code optimozation & Pass map instead of variables file to ansible script

- config.yaml
- config/config.go
Add launchTemplate details: launchTemplateId and launchTemplateVersion
> Add launchTemplate details

- GNUmakefile
- install_scaling_manager.yaml
1. Included copy of ansible.cfg and ansible_scripts dir in GNUMakefile
2. Added logic to ansible_script to copy pem file across the nodes
> Ansible and pem file copy

- config.yaml
- config/config.go
Read the region from user in configuration file
> Read AWS region

- utilities/utilities.go
> Fixed nodeMap Interface issue

- GNUmakefile
- install_scaling_manager.yaml
- scaling_manager.service
1) Changed the ownership for scaling manager lib
2) Do not delete the library or stop the already running scaling manager 
3) start,stop and restart using ansible module for scaling manager 
4) passing username and password from ansible playbook as extra vars 
5) Transfering the PEM fike
6) Fetching the status for scaling manager on all the nodes
> Changes related to ansible, makefile and service stop

- config/config.go
Remove validation for MonitorWithLogs
> Remove validation for MonitorWithLogs

- ansible_scripts/roles/scale_down/tasks/main.yml
- ansible_scripts/roles/scale_up/tasks/opensearch.yml
- ansible_scripts/roles/scale_up/tasks/security.yml
- ansible_scripts/scaleDownPlaybook.yml
- ansible_scripts/scaleUpPlaybook.yml
- provision/provision.go
1. Fixed interface issue while scaleDown
2. Update /etc/hosts on removal
3. Replaced copy module with shell command to bypass permission issue
4. Updated creation of unicast_hosts.txt file due to permission issues
5. Removed /etc/ansible/hosts update for each node as we use custom inventory file
> Fix issues:

- ansible_scripts/roles/scale_up/tasks/security.yml
- provision/provision.go
- provision/trigger.go
1. Check if new node spinned up has joined the cluster
2. Update trigger.go
3. Syntax fix for ansible script
> Check new node addition

- ansible_scripts/group_vars/all/all.yml
- ansible_scripts/roles/scale_down/tasks/main.yml
- ansible_scripts/roles/scale_up/tasks/opensearch.yml
- ansible_scripts/roles/scale_up/tasks/security.yml
- ansible_scripts/roles/scale_up/templates/opensearch.service
- ansible_scripts/scaleDownPlaybook.yml
- ansible_scripts/scaleUpPlaybook.yml
- provision/provision.go
- provision/trigger.go
1. Read group from user config
2. Update groups name in ansible hosts file
3. Updated comment
> Fix issues

- provision/provision.go
Check the node join and install scaling manager before moving the state to provision completed
> Check node join before scaleup is marked complete

- crypto/crypto_controller.go
- scaleManager/main.go
1. Update the secret file first and then the config.yaml
2. Update fileWatch to only check for the change in config.yaml file
> Update fileWatch() & update secret first

- ansible_scripts/callAnsible.go
- config/config.go
- crypto/crypto_controller.go
- provision/awsScale.go
- provision/provision.go
- scaleManager/main.go
- utilities/utilities.go
raised a PR from new branch.
1. Contains a fix for logic update
> Crypto controller changes

- provision/awsScale.go
Removed decrypt logic from awsScale.go since it was already done in provision.go
> Fix issue. 

- provision/provision.go
Decrypt once in every ScaleOut or ScaleIn
> Decrypt once in every provision

- scaleManager/main.go
1. There are changes of a data node detecting the change in encryption secret before config file is updated.
2. Therefore, making changes to update the global variable EncryptionSecret only after the config.yaml change is detected
> Check for config file change if not master

- cluster/cluster_level_parameters.go
- config.yaml
- fetchmetrics/fetchClusterMetrics.go
- recommendation/recommendationEngine.go
1. Added support for shard based scaling
2. Occurrences can now be percent or occurrences
3. Update config.yaml
4. Handle divide by zero
> Shard and occurrences

- README.md
- Added details on rules, updated simulator link from release_v0.1_dev
> -Added details on Readme

- cluster/cluster_level_parameters.go
- fetchmetrics/fetchClusterMetrics.go
- opensearchUtils/apiCalls.go
- provision/provision.go
- provision/trigger.go
1. Add a param to waitForNoRelocatingShards & NoInitializingShards before saying the provision is complete
> Wait for shards

- config.yaml
- config/config.go
- crypto/crypto_controller.go
- provision/awsScale.go
1. Add IAM Role ARN for creating AWS Session for connecting to ec2
> IAM Role based session

- GNUmakefile
The complete package as artifacts will be zipped.
> Reverting the logic to tar.gz

- ansible_scripts/roles/scale_up/tasks/opensearch.yml
Copy jvm.options template to Opensearch
> [BUG] jvm options copy

- cluster/cluster_level_parameters.go
- config.yaml
- recommendation/recommendationEngine.go
1. Removed TotalShards and replcaed with ShardsPerGB
2. Current changes from violated-count-query causes a panic due to query change
3. Removed the logic due to the above panic issue
4. Added comment to update the logic later for now
> Remove TotalShards recommendation

- cluster/cluster_level_parameters.go
- config/config.go
- fetchmetrics/fetchClusterMetrics.go
- provision/provision.go
- recommendation/recommendationEngine.go
- scaleManager/main.go
1. Move the Task structs from recommendation to config
2. Also, the tasks and rules are config specific not recommendation specific
3. Remove the import of config from Recommendation
4. Updated some log statements
> Resolve cyclic imports

- provision/awsScale.go
- provision/provision.go
- provision/state_functions.go
- recommendation/recommendationEngine.go
1. Separated instance creation and wait for instanc functions in awsScale.go
2. Instance status check is moved to next stage of scale_up
3. Immediately after instance check, the ansible script will be triggered
4. Store instance ID in OS to be used in next stage
> Move instance status check

- simulator/tests/config_test/config_1_P.yaml
- simulator/tests/config_test/config_2_P.yaml
- simulator/tests/config_test/config_3_P.yaml
- simulator/tests/config_test/config_4_F.yaml
- simulator/tests/config_test/config_5_F.yaml
- simulator/tests/config_test/config_6_F.yaml
- simulator/tests/test_config_parser.py
Test case for config_parser and to accommodate new config file.
Resolves #109
> Added test case for config_parser.

- main.go
- provision/ansible_scripts/ansible.cfg
- provision/ansible_scripts/docs.py
- provision/ansible_scripts/group_vars/all/all.yml
- provision/ansible_scripts/roles/scale_down/defaults/main.yml
- provision/ansible_scripts/roles/scale_down/handlers/main.yml
- provision/ansible_scripts/roles/scale_down/tasks/main.yml
- provision/ansible_scripts/roles/scale_down/vars/main.yml
- provision/ansible_scripts/roles/scale_up/defaults/main.yml
- provision/ansible_scripts/roles/scale_up/handlers/main.yml
- provision/ansible_scripts/roles/scale_up/tasks/ansible.cfg
- provision/ansible_scripts/roles/scale_up/tasks/install_ansible.yml
- provision/ansible_scripts/roles/scale_up/tasks/main.yml
- provision/ansible_scripts/roles/scale_up/tasks/opensearch.yml
- provision/ansible_scripts/roles/scale_up/tasks/security.yml
- provision/ansible_scripts/roles/scale_up/tasks/tune.yml
- provision/ansible_scripts/roles/scale_up/templates/internal_users.yml
- provision/ansible_scripts/roles/scale_up/templates/jvm.options
- provision/ansible_scripts/roles/scale_up/templates/opensearch-multi-node.yml
- provision/ansible_scripts/roles/scale_up/templates/opensearch.service
- provision/ansible_scripts/roles/scale_up/templates/security_conf.yml
- provision/ansible_scripts/roles/scale_up/templates/tlsconfig.yml
- provision/ansible_scripts/scaleDownPlaybook.yml
- provision/ansible_scripts/scaleUpPlaybook.yml
- provision/callAnsible.go
- provision/mappings.json
- provision/provision.go
- provision/scaleUpNode.go
- provision/state_functions.go
- provision/trigger.go
1. Added 2 different roles for scaleup/scaledown
2. Configures the nodes to add/remove node
3. Performs the changes on all other nodes necessary after scaleup/scaledown
4. Added go methods to call ansible scripts
5. Added flag to monitor with logs
> Actual provision

- provision/provision.go
Increase wait time for node to join the cluster
> Increase wait time for node to join the cluster

- cluster/cluster_level_parameters.go
- recommendation/recommendationEngine.go
> Query bug fix
